version: '3.8'

services:
  db:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql_eam
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL/data:/var/lib/mysql 
    hostname: apps_database
    env_file:
      - .env
    networks:
      - eam_apps
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eam_apps
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://apps_database:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer
    container_name: adminer_wms
    restart: always
    ports:
      - "8081:8080"
    networks:
      - eam_apps

networks:
  eam_apps:
    driver: bridge
